// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: Scanner.flex

/* Scanner.flex
 * JFlex specification for the lexical analyzer
 * Recognizes the same tokens as the ManualScanner with identical priority
 */

/* ==================== USER CODE SECTION ==================== */

@SuppressWarnings("fallthrough")
public class JFlexScanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\u10ff\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\2\0\1\1\22\0\1\3\1\4"+
    "\1\5\1\6\1\0\1\7\1\10\1\11\2\12\1\13"+
    "\1\14\1\12\1\15\1\16\1\17\12\20\2\12\1\21"+
    "\1\22\1\21\2\0\4\23\1\24\25\23\1\12\1\25"+
    "\1\12\1\0\1\26\1\0\1\27\1\30\1\31\1\32"+
    "\1\33\1\34\1\35\1\36\1\37\1\35\1\40\1\41"+
    "\1\35\1\42\1\43\1\44\1\35\1\45\1\46\1\47"+
    "\1\50\5\35\1\12\1\51\1\12\u0182\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[512];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\1\1\5\1\1"+
    "\1\6\1\7\4\5\1\10\1\11\1\12\1\13\14\14"+
    "\1\1\1\11\1\15\1\0\1\16\1\17\1\3\1\20"+
    "\1\0\1\12\1\21\1\22\1\0\15\14\1\0\1\23"+
    "\1\24\14\14\1\16\1\24\1\0\4\14\1\25\4\14"+
    "\1\26\1\24\1\0\1\24\5\14\1\24\2\14\2\24";

  private static int [] zzUnpackAction() {
    int [] result = new int[97];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\52\0\52\0\124\0\176\0\250\0\52\0\322"+
    "\0\374\0\52\0\u0126\0\u0150\0\u017a\0\u01a4\0\u01ce\0\124"+
    "\0\124\0\u01f8\0\u0222\0\u024c\0\u0276\0\u02a0\0\u02ca\0\u02f4"+
    "\0\u031e\0\u0348\0\u0372\0\u039c\0\u03c6\0\u03f0\0\u041a\0\52"+
    "\0\52\0\u0444\0\u046e\0\u0498\0\52\0\u04c2\0\u04ec\0\52"+
    "\0\52\0\52\0\u0516\0\u0540\0\u056a\0\u0594\0\u05be\0\u05e8"+
    "\0\u0612\0\u063c\0\u0666\0\u0690\0\u06ba\0\u06e4\0\u070e\0\u0738"+
    "\0\u0762\0\52\0\u078c\0\u07b6\0\u07e0\0\u080a\0\u0834\0\u085e"+
    "\0\u0888\0\u08b2\0\u08dc\0\u0906\0\u0930\0\u095a\0\u0984\0\52"+
    "\0\u09ae\0\u09d8\0\u0a02\0\u0a2c\0\u0a56\0\u0a80\0\u0222\0\u0aaa"+
    "\0\u0ad4\0\u0afe\0\u0b28\0\u0222\0\u0b52\0\u0b7c\0\u0b7c\0\u0ba6"+
    "\0\u0bd0\0\u0bfa\0\u0c24\0\u0c4e\0\u0c78\0\u0ca2\0\u0ccc\0\u0cf6"+
    "\0\u0d20";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[97];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\3\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\2\1\16\1\17\1\20"+
    "\1\21\2\22\2\2\1\23\1\24\1\25\1\26\1\27"+
    "\1\30\2\23\1\31\1\23\1\32\1\23\1\33\1\23"+
    "\1\34\1\35\1\36\1\23\1\37\74\0\1\40\27\0"+
    "\2\5\1\0\2\5\1\41\17\5\1\42\24\5\6\0"+
    "\1\43\4\0\1\44\46\0\1\45\41\0\2\46\1\0"+
    "\6\46\1\0\13\46\1\47\24\46\13\0\1\7\6\0"+
    "\1\50\43\0\1\51\5\0\1\50\44\0\1\52\4\0"+
    "\1\50\51\0\1\50\45\0\1\53\1\0\1\17\34\0"+
    "\1\22\14\0\1\22\5\0\23\22\21\0\1\23\5\0"+
    "\23\23\21\0\1\23\5\0\17\23\1\54\3\23\21\0"+
    "\1\23\5\0\15\23\1\55\5\23\21\0\1\23\5\0"+
    "\5\23\1\56\15\23\21\0\1\23\5\0\13\23\1\57"+
    "\7\23\21\0\1\23\5\0\1\23\1\60\7\23\1\61"+
    "\10\23\1\62\21\0\1\23\5\0\14\23\1\63\6\23"+
    "\21\0\1\23\5\0\15\23\1\64\5\23\21\0\1\23"+
    "\5\0\22\23\1\65\21\0\1\23\5\0\5\23\1\66"+
    "\15\23\21\0\1\23\5\0\21\23\1\67\1\23\21\0"+
    "\1\23\5\0\17\23\1\70\3\23\52\0\1\45\5\0"+
    "\1\5\17\0\1\5\14\0\1\5\2\0\1\5\1\0"+
    "\1\5\2\0\2\43\1\0\47\43\13\44\1\71\36\44"+
    "\11\0\1\72\51\0\1\46\13\0\1\46\14\0\1\46"+
    "\2\0\1\46\1\0\1\46\22\0\1\73\51\0\1\23"+
    "\5\0\5\23\1\74\15\23\21\0\1\23\5\0\14\23"+
    "\1\75\6\23\21\0\1\23\5\0\3\23\1\76\17\23"+
    "\21\0\1\23\5\0\20\23\1\77\2\23\21\0\1\23"+
    "\5\0\13\23\1\100\7\23\21\0\1\23\5\0\14\23"+
    "\1\101\6\23\21\0\1\23\5\0\14\23\1\102\6\23"+
    "\21\0\1\23\5\0\16\23\1\103\4\23\21\0\1\23"+
    "\5\0\15\23\1\104\5\23\21\0\1\23\5\0\21\23"+
    "\1\63\1\23\21\0\1\23\5\0\21\23\1\105\1\23"+
    "\21\0\1\23\5\0\1\23\1\106\21\23\21\0\1\23"+
    "\5\0\22\23\1\107\1\0\6\44\1\110\4\44\1\71"+
    "\36\44\20\0\1\111\3\0\1\112\6\0\1\112\36\0"+
    "\1\23\5\0\1\23\1\113\21\23\21\0\1\23\5\0"+
    "\4\23\1\114\14\23\1\115\1\23\21\0\1\23\5\0"+
    "\13\23\1\116\7\23\21\0\1\23\5\0\5\23\1\117"+
    "\15\23\21\0\1\23\5\0\20\23\1\107\2\23\21\0"+
    "\1\23\5\0\11\23\1\120\11\23\21\0\1\23\5\0"+
    "\3\23\1\121\17\23\21\0\1\23\5\0\22\23\1\122"+
    "\21\0\1\23\5\0\16\23\1\117\4\23\21\0\1\23"+
    "\5\0\22\23\1\123\21\0\1\23\5\0\17\23\1\122"+
    "\3\23\21\0\1\23\5\0\5\23\1\124\15\23\21\0"+
    "\1\125\3\0\1\112\6\0\1\112\32\0\2\126\2\0"+
    "\1\127\51\0\1\23\5\0\12\23\1\117\10\23\21\0"+
    "\1\23\5\0\11\23\1\121\11\23\21\0\1\23\5\0"+
    "\11\23\1\130\11\23\21\0\1\23\5\0\1\23\1\131"+
    "\21\23\21\0\1\23\5\0\20\23\1\132\2\23\21\0"+
    "\1\23\5\0\21\23\1\133\1\23\21\0\1\23\5\0"+
    "\21\23\1\117\1\23\21\0\1\23\5\0\17\23\1\134"+
    "\3\23\21\0\1\135\3\0\1\112\6\0\1\112\36\0"+
    "\1\127\51\0\1\23\5\0\14\23\1\136\6\23\21\0"+
    "\1\23\5\0\17\23\1\77\3\23\21\0\1\23\5\0"+
    "\10\23\1\117\12\23\21\0\1\23\5\0\11\23\1\137"+
    "\11\23\21\0\1\23\5\0\14\23\1\117\6\23\21\0"+
    "\1\140\3\0\1\112\6\0\1\112\36\0\1\23\5\0"+
    "\22\23\1\77\21\0\1\23\5\0\15\23\1\134\5\23"+
    "\21\0\1\141\3\0\1\112\6\0\1\112\42\0\1\112"+
    "\6\0\1\112\16\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[3402];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\3\1\1\11\2\1\1\11\25\1\2\11"+
    "\1\0\2\1\1\11\1\1\1\0\3\11\1\0\15\1"+
    "\1\0\1\11\15\1\1\11\1\1\1\0\13\1\1\0"+
    "\13\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[97];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
    /* ---- Imports and helper fields ---- */
    private java.util.List<Token> tokens = new java.util.ArrayList<>();
    private SymbolTable symbolTable = new SymbolTable();
    private ErrorHandler errorHandler = new ErrorHandler();

    /* Statistics */
    private java.util.Map<TokenType, Integer> tokenCounts = new java.util.HashMap<>();
    private int totalTokens = 0;
    private int commentsRemoved = 0;

    /* ---- Helper methods ---- */

    /** Adds a token and updates statistics */
    private Token addToken(TokenType type, String lexeme) {
        Token t = new Token(type, lexeme, yyline + 1, yycolumn + 1);
        tokens.add(t);
        tokenCounts.put(type, tokenCounts.getOrDefault(type, 0) + 1);
        totalTokens++;
        return t;
    }

    /** Scans the entire input and returns all tokens */
    public java.util.List<Token> scanAll() throws java.io.IOException {
        Token t;
        while ((t = yylex()) != null) {
            // tokens are already added in addToken()
        }
        return tokens;
    }

    /** Returns all tokens after scanning */
    public java.util.List<Token> getTokens() { return tokens; }

    /** Returns the symbol table */
    public SymbolTable getSymbolTable() { return symbolTable; }

    /** Returns the error handler */
    public ErrorHandler getErrorHandler() { return errorHandler; }

    /** Prints all tokens */
    public void printTokens() {
        System.out.println("\n========== TOKENS ==========");
        for (Token token : tokens) {
            System.out.println(token);
        }
        System.out.println("============================\n");
    }

    /** Prints statistics */
    public void printStatistics() {
        System.out.println("\n========== STATISTICS ==========");
        System.out.println("Total Tokens: " + totalTokens);
        System.out.println("Lines Processed: " + (yyline + 1));
        System.out.println("Comments Removed: " + commentsRemoved);
        System.out.println("Errors Detected: " + errorHandler.getErrorCount());
        System.out.println("\nToken Count by Type:");
        System.out.println("-".repeat(40));

        tokenCounts.entrySet().stream()
                .sorted(java.util.Map.Entry.comparingByKey(java.util.Comparator.comparing(Enum::name)))
                .forEach(entry -> {
                    System.out.printf("%-25s: %d\n", entry.getKey(), entry.getValue());
                });

        System.out.println("=".repeat(40));

        if (errorHandler.hasErrors()) {
            errorHandler.printErrorSummary();
        }
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public JFlexScanner(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public Token yylex() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { errorHandler.reportInvalidCharacter(yytext().charAt(0), yyline + 1, yycolumn + 1); 
                            /* continue scanning after error */
            }
          // fall through
          case 23: break;
          case 2:
            { /* skip - return null to continue */
            }
          // fall through
          case 24: break;
          case 3:
            { return addToken(TokenType.LOGICAL_OP, yytext());
            }
          // fall through
          case 25: break;
          case 4:
            { errorHandler.reportUnterminatedString(yytext(), yyline + 1, yycolumn + 1);
                            /* continue scanning after error */
            }
          // fall through
          case 26: break;
          case 5:
            { return addToken(TokenType.ARITHMETIC_OP, yytext());
            }
          // fall through
          case 27: break;
          case 6:
            { errorHandler.reportUnterminatedChar("'", yyline + 1, yycolumn + 1);
                            /* continue scanning after error */
            }
          // fall through
          case 28: break;
          case 7:
            { return addToken(TokenType.PUNCTUATOR, yytext());
            }
          // fall through
          case 29: break;
          case 8:
            { return addToken(TokenType.INTEGER_LITERAL, yytext());
            }
          // fall through
          case 30: break;
          case 9:
            { return addToken(TokenType.RELATIONAL_OP, yytext());
            }
          // fall through
          case 31: break;
          case 10:
            { return addToken(TokenType.ASSIGNMENT_OP, yytext());
            }
          // fall through
          case 32: break;
          case 11:
            { String word = yytext().stripTrailing();
                                if (word.length() > 31) {
                                    System.out.println("Warning: Identifier too long (max 31 chars) at Line: " +
                                            (yyline + 1) + ", Col: " + (yycolumn + 1) + " - truncating");
                                    word = word.substring(0, 31);
                                }
                                symbolTable.addSymbol(word, "IDENTIFIER", yyline + 1, yycolumn + 1);
                                return addToken(TokenType.IDENTIFIER, word);
            }
          // fall through
          case 33: break;
          case 12:
            { String word = yytext();
                                /* Check if it is a keyword or boolean that wasn't caught above */
                                java.util.Set<String> kw = new java.util.HashSet<>(java.util.Arrays.asList(
                                    "start","finish","loop","condition","declare","output",
                                    "input","function","return","break","continue","else"));
                                java.util.Set<String> bl = new java.util.HashSet<>(java.util.Arrays.asList("true","false"));
                                if (kw.contains(word)) {
                                    return addToken(TokenType.KEYWORD, word);
                                } else if (bl.contains(word)) {
                                    return addToken(TokenType.BOOLEAN_LITERAL, word);
                                } else {
                                    errorHandler.reportInvalidIdentifier(word, yyline + 1, yycolumn + 1,
                                        "Identifier '" + word + "' must start with an uppercase letter");
                                    /* continue scanning after error */
                                }
            }
          // fall through
          case 34: break;
          case 13:
            { return addToken(TokenType.STRING_LITERAL, yytext());
            }
          // fall through
          case 35: break;
          case 14:
            { commentsRemoved++; /* skip - return null to continue */
            }
          // fall through
          case 36: break;
          case 15:
            { commentsRemoved++; 
                            errorHandler.reportUnclosedComment(yyline + 1, yycolumn + 1); 
                            /* skip - return null to continue */
            }
          // fall through
          case 37: break;
          case 16:
            { errorHandler.reportUnterminatedChar(yytext(), yyline + 1, yycolumn + 1);
                            /* continue scanning after error */
            }
          // fall through
          case 38: break;
          case 17:
            { return addToken(TokenType.INCREMENT_OP, yytext());
            }
          // fall through
          case 39: break;
          case 18:
            { return addToken(TokenType.DECREMENT_OP, yytext());
            }
          // fall through
          case 40: break;
          case 19:
            { return addToken(TokenType.CHAR_LITERAL, yytext());
            }
          // fall through
          case 41: break;
          case 20:
            { return addToken(TokenType.FLOAT_LITERAL, yytext());
            }
          // fall through
          case 42: break;
          case 21:
            { /* Check if it's followed by a delimiter to avoid partial matches */
                            String word = yytext();
                            return addToken(TokenType.KEYWORD, word);
            }
          // fall through
          case 43: break;
          case 22:
            { String word = yytext(); 
                            return addToken(TokenType.BOOLEAN_LITERAL, word);
            }
          // fall through
          case 44: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
